### ISSUE TITLE
How to avoid signal race condition when creating new ClientProxy object?

### ISSUE THREAD

**Issue by dlech** [dbusjs/node-dbus-next#55]
When calling `getProxyObject()` it optionally asynchronous calls the D-Bus introspection method and then asynchronously parses XML before resolving the promise. During this time, it is possible to receive signals for this object, but they are missed since we can't attach signal handlers yet (even if XML is supplied and introspection step is skipped, it takes too long).

Real-world case: I'm trying to use this library with Avahi. It has methods (e.g. `ServiceBrowserNew`) that create a new D-Bus object and return the object path. Then we take the path and create a new proxy object. However, these objects immediately start receiving signals (e.g. `ItemNew`) as can be seen using the `dbus-monitor` command line tool. However `dbus-next` misses these because the signals happen before we ever get a proxy object.

How can we avoid this race condition?

**Comment by acrisci** [comment]
I don't believe the problem is caused by xml parsing. AFIK that happens synchronously if you provide xml because the callback for parsing xml happens immediately.

What's probably causing the race condition is the match rule. When you add an event handler, it will asynchronously add a match rule for the interface member to start getting signals. If the match rule were more broad and happened before calling `ServiceBrowserNew`, it would probably resolve the issue.

You can experiment with adding a custom match rule to the bus with the low level interface for the whole bus address and see if that fixes it. Here's an example of how to do that from the test suite:

```js
  let addMatchMessage = new Message({
    destination: 'org.freedesktop.DBus',
    path: '/org/freedesktop/DBus',
    interface: 'org.freedesktop.DBus',
    member: 'AddMatch',
    signature: 's',
    body: [`sender='${bus2.name}'`]
  });
  await bus1.call(addMatchMessage)
```

If some tweaking is needed to support Avahi, I would accept a patch to fix this in the library so you don't have to use a workaround.

**Comment by dlech** [comment]
Thanks for the feedback. (I think I was seeing things that were not really there with the XML :confused:).

I found [this issue](https://github.com/lathiat/avahi/issues/9) where this problem is discussed. It looks like it is fixed in Avahi 0.8 but it will probably be quite a few years before it makes it onto most users computers.

So, yeah, I will probably have to make something that listens to all signals and that can queue and replay them.

**Comment by acrisci** [comment]
You can just alter your code to add the match rule before you make the proxy object and it should work.

**Comment by dlech** [comment]
How do you add an event listener to listen for signals from this match before the proxy is created?

**Comment by dlech** [comment]
Found it:

```javascript
bus.on('message', (msg) => {
    debugger;
});
```

**Comment by acrisci** [comment]
If the low level interface works best for you, that's fine. If you want to get the proxy object to work, follow my previous instructions.

**Comment by dlech** [comment]
I did follow your instructions, but the signals still occur before the proxy object can be created and event handlers can't be added until after the proxy object is created. The event listeners have to be added before the `ServiceBrowserNew` is even called otherwise signals are missed. So using the low-level interface is the only way to make it work race-free.

**Comment by acrisci** [comment]
Oh ok. Then this is clearly incompatible with any proxy object implementation.
