### ISSUE TITLE
How to unmarshal results from GetAll()?

### ISSUE THREAD

**Issue by frederikheld** [dbusjs/node-dbus-next#68]
Hey,

this is some code I wrote to scan for available wireless access points on a given device and get their properties.

I can't guarantee that this example works as I stripped out some stuff to simplify it. But it should serve the purpose to illustrate how the result below is created.

```js
'use strict'

// params:
const device_name = 'wlan0'

// config:
const dbusBaseName = 'org.freedesktop.NetworkManager'
const dbusBasePath = '/org/freedesktop/NetworkManager'
const dbusPropertiesName = 'org.freedesktop.DBus.Properties'

// setup dbus stuff:
const bus = dbus.systemBus()
const proxyObject = await this.bus.getProxyObject(dbusBaseName, dbusBasePath)
const propertiesInterface = proxyObject.getInterface(dbusPropertiesName)
const managerInterface = proxyObject.getInterface(dbusBaseName)

// get list of network interfaces on the given device:
const device_path = await managerInterface.GetDeviceByIpIface(device_name)
const deviceProxyObject = await this.bus.getProxyObject(this.dbusBaseName, device_path)
const deviceInterfaceNames = Object.keys(deviceProxyObject.interfaces)

// check if it has wireless capabilities:
if (deviceInterfaceNames.includes(this.dbusBaseName + '.Device.Wireless')) {
    // get the wireless interface:
    const deviceManagerInterface = deviceProxyObject.getInterface(dbusBaseName + '.Device.Wireless')

    // request a scan for available access points, then fetch the list:
    deviceManagerInterface.RequestScan({})
    const accessPointPaths = await new Promise(async (resolve, reject) => {
        const promiseScan = new Promise((resolve, reject) => {
            deviceManagerInterface.on('AccessPointAdded', (iface, changed, invalidated) => {
                resolve()
            })
        })

        const promiseTimeout = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve()
            }, 5000)
        })

        await Promise.race([promiseScan, promiseTimeout])
        
        resolve(deviceManagerInterface.GetAllAccessPoints())
    })

    // Get properties of access points (this is a loop, I picked one item as an example):
    const apProxyObject = await bus.getProxyObject(dbusBaseName, accessPointPaths[0])
    const apPropertiesInterface = apProxyObject.getInterface(dbusPropertiesName)
    const allProperties = await apPropertiesInterface.GetAll(dbusBaseName + '.AccessPoint')

    // print:
    console.log(allProperties)
}
```

It took me ages to get to this point because the docs neither DBus, nor NetworkManager, nor this library are very helpful if you don't already know how this stuff works.

The above code prints the following:

```js
{
  Flags: Variant { signature: 'u', value: 1 },
  WpaFlags: Variant { signature: 'u', value: 0 },
  RsnFlags: Variant { signature: 'u', value: 392 },
  Ssid: Variant { signature: 'ay', value: <Buffer 46 52 49 54 5a 21 42 6f 78 20 47 61 73 74 7a 75 67 61 6e 67> },
  Frequency: Variant { signature: 'u', value: 5220 },
  HwAddress: Variant { signature: 's', value: 'E0:18:60:6F:50:46' },
  Mode: Variant { signature: 'u', value: 2 },
  MaxBitrate: Variant { signature: 'u', value: 540000 },
  Strength: Variant { signature: 'y', value: 78 },
  LastSeen: Variant { signature: 'i', value: 28070 }
}
```
I understand the signatures approach of DBus and I spent quite some time to figure out if there is any mechanism to unmarshal those values with some built-in functions of `dbus-next`. I found it in the code but I didn't figure out how to apply it. Do I have to load some function to unmarshal this. Or should there be any method I can use on Variants to get the value? 

The result should be an object with the same structure as the above, but instead of the Variant I would like to have the unmarshalled values. Which function can I use to do this?

Is this even the right approach? Shouldn't this be way easier?

Thanks in advance,
Fred

**Comment by acrisci** [comment]
The return signature from `GetAll` is `a{sv}` which means you are guaranteed to have string keys and `Variant` values, so every object value will be a variant. You can access the value with `obj['key'].value`.

The `Variant` is exposed in user code to follow the spirit of the spec. This type is purposefully transmitted with type information as part of the value and that may be useful to some application.

This could be easier, but I don't think it could be way easier. In this particular case, we already know all the type information for the properties because that's in the introspection already. We could expose some methods on the interface itself without needing the dbus properties interface. That method could safely unbox the value from the variant because you already know the type. I use this approach on another dbus library I wrote. I should bring it here, but it gets a little complicated because of namespacing issues since any method I add to a proxy interface might conflict with an existing method in the introspection. That probably wouldn't be that difficult to solve. If I went that way, you could do something like:

```javascript
apProxyObject.getAllProperties()
```

and it would do what you would expect. (It's complicated if the introspection already contains a method called `getAllProperties`.)

I wouldn't add a special exception to a proxy interface for the dbus properties interface because it would be surprising for that to work differently.

As for a method to automatically unbox variants as a utility, that's something people have requested and I wouldn't be opposed to putting it in the library. It's already written in the internal code and could be exposed to the user. It would also be useful in serialization.

**Comment by frederikheld** [comment]
Thanks for your answer. I had thought of something more straightforward. Like a unmarshall() methods for the Variants class. Then I could do an array map over the results of GetAll().

Your library already has a couple of internal functions to marshall/unmarshall in messages.js, marshallers.js and marshall-compat.js. Is there any way I can make use of those? Which one would be the one that helps me here?

**Comment by acrisci** [comment]
The `Variant` class is already completely unmarshalled. The word "unmarshal" means to turn the bytes we get over the wire into an object in the language. You can access the unmarshalled value with the `value` member of the class.

**Comment by frederikheld** [comment]
"The Variant class is already completely unmarshalled" <-- that's not what I see.

The result of GetAll contains Variants objects. If I do `console.log(result.Ssid.value)` it prints byte buffers. I have to do `console.log(result.Ssid.value.toString())` to get it as a string.

**Comment by acrisci** [comment]
The `ay` type is "list of bytes" which is unmarshalled by the library as a node `Buffer` class. These values represent binary data that may not necessarily be valid utf-8 strings. It could be a picture to show with a desktop notification or an audio buffer that's being sent from a bluetooth device. Since the protocol indicates it is just sending you general data, there's no further unmarshalling we can do on this type.

**Comment by frederikheld** [comment]
Ah, I understand now. So the underlying "problem" is that NetworkManager sends Ssid's as `ay` instead of `s`? And I have to know for myself that this needs to be converted into a string to make sense to the user? KK, got it.

**Comment by frederikheld** [comment]
But why do I get Variants objects that contain signature information if the value is already unmarshalled? What would I do with that information?

**Comment by acrisci** [comment]
You don't need it for your application. Signature strings are useful because they convey information about the value that can't be expressed by the js type system. For instance, we know type `u` is a `Number` that will never be negative. You don't need to do that validation in your code because the library won't process the message otherwise.
